### ISSUE TITLE
Unable to execute create_service_math_shepherd successfully

### ISSUE THREAD

**Issue by rocky-lq** [openreasoner/openr#19]
I couldn't execute the following script successfully:
```
sh reason/llm_service/create_service_math_shepherd.sh
```
The error message is as follows:
```
2024-10-18 17:05:54 | ERROR | stderr | 
2024-10-18 17:06:11 | INFO | model_worker | Register to controller
2024-10-18 17:06:11 | INFO | stdout | <Response [503]>
2024-10-18 17:06:11 | ERROR | stderr | Traceback (most recent call last):
2024-10-18 17:06:11 | ERROR | stderr |   File "/open_reasonser/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-10-18 17:06:11 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-10-18 17:06:11 | ERROR | stderr |   File "/open_reasonser/lib/python3.10/runpy.py", line 86, in _run_code
2024-10-18 17:06:11 | ERROR | stderr |     exec(code, run_globals)
2024-10-18 17:06:11 | ERROR | stderr |   File "/openr/reason/llm_service/workers/reward_model_worker.py", line 255, in <module>
2024-10-18 17:06:11 | ERROR | stderr |     args, worker = create_model_worker()
2024-10-18 17:06:11 | ERROR | stderr |   File "/openr/reason/llm_service/workers/reward_model_worker.py", line 227, in create_model_worker
2024-10-18 17:06:11 | ERROR | stderr |     worker = ModelWorker(
2024-10-18 17:06:11 | ERROR | stderr |   File "/openr/reason/llm_service/workers/reward_model_worker.py", line 109, in __init__
2024-10-18 17:06:11 | ERROR | stderr |     self.init_heart_beat()
2024-10-18 17:06:11 | ERROR | stderr |   File "/openr/reason/llm_service/workers/base_model_worker.py", line 79, in init_heart_beat
2024-10-18 17:06:11 | ERROR | stderr |     self.register_to_controller()
2024-10-18 17:06:11 | ERROR | stderr |   File "/openr/reason/llm_service/workers/base_model_worker.py", line 98, in register_to_controller
2024-10-18 17:06:11 | ERROR | stderr |     assert r.status_code == 200
2024-10-18 17:06:11 | ERROR | stderr | AssertionError
```

How can I resolve this issue?

**Comment by YanSong97** [comment]
Hi rocky, this seems relevant to #18 .

**Comment by rocky-lq** [comment]
I am unable to run the following script:
```
sh reason/llm_service/create_service_math_shepherd.sh
```
I’m using 8 * A100 80G GPUs. I encounter the same error even after making the following adjustments:

1. I’ve modified `POLICY_MODEL_NAME` and `VALUE_MODEL_NAME` to point to my local paths.
2. I’ve installed `vllm=0.6.1.post2`.

However, the issue persists. Could you please advise if there are any additional configurations needed or suggest any debugging steps?

**Comment by ziyuwan** [comment]
> I am unable to run the following script:
> 
> ```
> sh reason/llm_service/create_service_math_shepherd.sh
> ```
> 
> I’m using 8 * A100 80G GPUs. I encounter the same error even after making the following adjustments:
> 
> 1. I’ve modified `POLICY_MODEL_NAME` and `VALUE_MODEL_NAME` to point to my local paths.
> 2. I’ve installed `vllm=0.6.1.post2`.
> 
> However, the issue persists. Could you please advise if there are any additional configurations needed or suggest any debugging steps?

Hi Rocky!

Can you show me the logs or attach into tmux sessions to check the error message?

**Comment by rocky-lq** [comment]
It seems to be an issue with the proxy. After unsetting the proxy using the following command, it works:
```
tmux send-keys "unset http_proxy && unset https_proxy && unset HTTPS_PROXY" Enter
```
