### ISSUE TITLE
train_math.py model file save error

### ISSUE THREAD

**Issue by Tshiyao** [openreasoner/openr#78]
### System Info

ubuntu20
python=3.10
A100-SXM4-80GB 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the codebase (such as scrips/, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
save model
total_num_steps:  64
average_step_rewards:  0.7349994
Process Process-5:
Traceback (most recent call last):
  File "/root/.conda/envs/open122/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/.conda/envs/open122/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/openr/train/mat/scripts/../../mat/envs/math/math_env_wrappers.py", line 117, in shareworker
    cmd, data = remote.recv()
  File "/root/.conda/envs/open122/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/root/.conda/envs/open122/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/.conda/envs/open122/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

```bash

total 17
drwxr-xr-x 2 root root 4096 Dec  6 22:02 ./
drwxr-xr-x 4 root root 4096 Dec  6 22:02 ../
-rw-r--r-- 1 root root 5119 Dec  6 22:02 README.md
-rw-r--r-- 1 root root  667 Dec  6 22:02 adapter_config.json
-rw-r--r-- 1 root root   40 Dec  6 22:02 adapter_model.safetensors
```

### Expected behavior

The program should exit normally, and the model weights should be saved properly.

**Comment by suanflower** [comment]
The same error, have you solved it?

**Comment by yy0525** [comment]
同样的错误

**Comment by meijuanwang** [comment]
同样的错误，感觉和设置了多个train env 有关，有没有哪位大佬解决了呀
